name: Docker Build & Push

on: 
    workflow_dispatch:
    #push:
    #    branches: [main]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:

            - name: Code Checkout
              uses: actions/checkout@v4

              # Enables cross-platform builds, QEMU is required when building images for a different CPU architecture
              # than the host machine. In CI systems like GitHub Actions, runners are typically amd64, 
              # so to build arm64 images we enable QEMU emulation along with Docker Buildx.
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

              # Enables Docker Buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USER }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - name: Build & Push to Docker Hub
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                platforms: linux/amd64,linux/arm64
                tags: |
                    ${{ vars.DOCKERHUB_USER }}/github-actions-app:latest
                    ${{ vars.DOCKERHUB_USER }}/github-actions-app:${{ github.ref_name }}
                    ${{ vars.DOCKERHUB_USER }}/github-actions-app:${{ github.sha}}
