# Workflow name
name: Hello World

# runs on automatic trigger, whenever developer push changes to branch (deployment)
on:
  push:
    branches: [main]
    paths: 
      - '**.html'
  workflow_dispatch:

  pull_request:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: say hello world
        run : echo "Hello World"

      - name: say hello to user
        run : echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name : version of python, docker etc
        run : python --version && docker --version
        
